apiVersion: v1
kind: Service
metadata:
  name: api
  labels:
    name: api
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 3000
    targetPort: 3000
  selector:
    name: aks-api
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name:  aks-api-deploy
  labels:
    name:  aks-api
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        name:  aks-api
    spec:
      imagePullSecrets:
        - name: acr-secret
      containers:
      - image: acralpha.azurecr.io/aks-api:v1
        name:  aks-api-cntnr
        resources:
          requests:
            cpu: "20m"
            memory: "55M"
        env:
        - name:  MONGODB_URI
          value:  mongodb://mongodb:27017/webratings
        ports:
        - containerPort:  3000
          name:  aks-api
        imagePullPolicy: Always
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: aks
  labels:
    name: aks
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    name: aks-web
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name:  aks-web-deploy
  labels:
    name:  aks-web
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        name:  aks-web
    spec:
      imagePullSecrets:
        - name: acr-secret
      containers:
      - image: acralpha.azurecr.io/aks:v1
        name:  aks-web-cntnr
        resources:
          requests:
            cpu: "0.5"
            memory: "1Gi"
        env:
        - name:  API
          value:  http://api:3000/
        - name: KUBE_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: KUBE_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: KUBE_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        ports:
        - containerPort:  8080
          name:  aks-web
        imagePullPolicy: Always
      restartPolicy: Always